### ISSUE TITLE
wildcard does not work under win10

### ISSUE THREAD

**Issue by d3vil7** [shushcli/shush#2]
under windows 10:

R:\>shush.exe merge my.key.*
Error: You must supply at least 2 shards to attempt to combine them into a secret

**Comment by shushcli** [comment]
Thanks for reporting!

Apparently windows shell doesn't expand wildcards.
I'll update the readme to indicate the wildcard only works on unix.

Here's the (closed) golang issue, if you're curious: https://github.com/golang/go/issues/3415
